name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/list-team:v2
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/list-team:cache
      
      - name: Pull Docker image
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/list-team:v2

      - name: docker run
        run: |
          CONTAINER_ID=$(docker run --rm -d -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/list-team:v2)

          # Wait for the service to be available
          for i in {1..10}; do
            if curl --fail http://127.0.0.1:8080/health; then
                    break
                  fi
                  echo "Waiting for service..."
                  sleep 3
          done

          curl http://127.0.0.1:8080/team-table

          docker stop $CONTAINER_ID